### ISSUE TITLE
Failed to load the compass package

### ISSUE THREAD

**Issue by abhishek1234321** [CristinaSolana/atom-compass-framework#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [compass](https://github.com/cristinasolana/atom-compass-framework) package, v0.7.5

### Stack Trace

Failed to load the compass package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/abhishek1/.atom/packages/compass/lib/compass-view.coffee:4:199)
  at /Users/abhishek1/.atom/packages/compass/lib/compass-view.coffee:5:3
  at Object.<anonymous> (/Users/abhishek1/.atom/packages/compass/lib/compass-view.coffee:52:5)
  at Object.<anonymous> (/Users/abhishek1/.atom/packages/compass/lib/compass-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/abhishek1/.atom/packages/compass/lib/compass.coffee:1:15)
  at Object.<anonymous> (/Users/abhishek1/.atom/packages/compass/lib/compass.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:711:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:433:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:316:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -3:03.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:03.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:02.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:58.5.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -2:57.9.0 core:undo (atom-text-editor.editor.is-focused)
 11x -2:56.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:53.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:43.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:40.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:37.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:37.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:34.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:21.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:21 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
auto-update-packages, v0.2.2
autocomplete-plus, v2.13.1
color-picker, v1.7.0
compass, v0.7.5
emmet-atom, v2.3.9
linter, v0.12.2
project-manager, v1.15.5
trailing-spaces, v0.2.5
turbo-javascript, v0.0.8

# Dev
No dev packages
```

**Comment by CristinaSolana** [comment]
Thanks for the heads up. Should be fixed.
